Fixed yaml indentation in action

diff --git a/.github/actions/run-tests/action.yml b/.github/actions/run-tests/action.yml
--- a/.github/actions/run-tests/action.yml
+++ b/.github/actions/run-tests/action.yml
@@ -11,35 +11,35 @@ runs:
 
   steps:
     - uses: marocchino/sticky-pull-request-comment@v2
-    with:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      header: tests
-      delete: true
+      with:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        header: tests
+        delete: true
 
-  - id: unittests
-    env:
-      QT_QPA_PLATFORM: offscreen
-    run: ./build/bin/unittests
-    continue-on-error: true
+    - id: unittests
+      env:
+        QT_QPA_PLATFORM: offscreen
+      run: ./build/bin/unittests
+      continue-on-error: true
 
-  - id: integtests
-    env:
-      QT_QPA_PLATFORM: offscreen
-    run: ./build/bin/integtests
-    continue-on-error: true
+    - id: integtests
+      env:
+        QT_QPA_PLATFORM: offscreen
+      run: ./build/bin/integtests
+      continue-on-error: true
 
-  - uses: marocchino/sticky-pull-request-comment@v2
-    env:
-      URL: https://github.com/symless/synergy-core/actions/workflows/valgrind-analysis.yml
-    with:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      append: true
-      message: |
-        - **${{ inputs.job }}**
-          unittests: ${{ steps.unittests.outcome == 'success' && '✅' || '❌' }}
-          integtests: ${{ steps.integtests.outcome == 'success' && '✅' || '❌' }}
+    - uses: marocchino/sticky-pull-request-comment@v2
+      env:
+        URL: https://github.com/symless/synergy-core/actions/workflows/valgrind-analysis.yml
+      with:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        append: true
+        message: |
+          - **${{ inputs.job }}**
+            unittests: ${{ steps.unittests.outcome == 'success' && '✅' || '❌' }}
+            integtests: ${{ steps.integtests.outcome == 'success' && '✅' || '❌' }}
 
-  - if: steps.unittests.outcome == 'failure'
-    run: |
-      echo "Unit tests failed"
-      exit 1
+    - if: steps.unittests.outcome == 'failure'
+      run: |
+        echo "Unit tests failed"
+        exit 1
