Retry pi

diff --git a/.github/workflows/job-changelog-check.yml b/.github/workflows/job-changelog-check.yml
--- a/.github/workflows/job-changelog-check.yml
+++ b/.github/workflows/job-changelog-check.yml
@@ -5,35 +5,35 @@
 # file with configuration.  For more information, see:
 # https://github.com/actions/labeler/blob/master/README.md
 
-name: ChangeLog Updated
-on: 
-  pull_request:
-    branches: [ master ]
+# name: ChangeLog Updated
+# on: 
+#   pull_request:
+#     branches: [ master ]
 
-jobs:
-  check:
-    runs-on: ubuntu-latest
-    steps:
-    - id: file_changes
-      name: Get changed files
-      uses: trilom/file-changes-action@v1.2.3
-      with:
-        output: ','
-    - name: echo changes
-      run: |
-        echo Files
-        echo '${{ steps.file_changes.outputs.files}}'
-        echo Modified
-        echo '${{ steps.file_changes.outputs.files_modified}}'
-        echo Added
-        echo '${{ steps.file_changes.outputs.files_added}}'
-        echo Removed
-        echo '${{ steps.file_changes.outputs.files_removed}}' 
-    - name: List files
-      run: |
-        if [[ "${{ steps.file_changes.outputs.files_modified}}" == *"ChangeLog"* ]]; then
-          echo "ChangeLog has been updated"
-        else
-          echo "::error file=app.js,line=10,col=15::Changelog hasn't been updated"
-          exit 1
-        fi
+# jobs:
+#   check:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - id: file_changes
+#       name: Get changed files
+#       uses: trilom/file-changes-action@v1.2.3
+#       with:
+#         output: ','
+#     - name: echo changes
+#       run: |
+#         echo Files
+#         echo '${{ steps.file_changes.outputs.files}}'
+#         echo Modified
+#         echo '${{ steps.file_changes.outputs.files_modified}}'
+#         echo Added
+#         echo '${{ steps.file_changes.outputs.files_added}}'
+#         echo Removed
+#         echo '${{ steps.file_changes.outputs.files_removed}}' 
+#     - name: List files
+#       run: |
+#         if [[ "${{ steps.file_changes.outputs.files_modified}}" == *"ChangeLog"* ]]; then
+#           echo "ChangeLog has been updated"
+#         else
+#           echo "::error file=app.js,line=10,col=15::Changelog hasn't been updated"
+#           exit 1
+#         fi
