Surface warning on failure

diff --git a/.github/workflows/sonarcloud-analysis.yml b/.github/workflows/sonarcloud-analysis.yml
--- a/.github/workflows/sonarcloud-analysis.yml
+++ b/.github/workflows/sonarcloud-analysis.yml
@@ -75,7 +75,13 @@ jobs:
       - name: Integration tests coverage
         env:
           QT_QPA_PLATFORM: offscreen
-        run: cmake --build build --target coverage-integtests
+        run: |
+          cmake --build build --target coverage-integtests
+          result=$?
+
+          if [ $result -ne 0 ]; then
+            echo "::warning ::Integration tests failed with code: $result"
+          fi
         continue-on-error: true
 
       - name: Get coverage report paths
