Update coverage paths for SonarCloud

diff --git a/.github/workflows/sonarcloud-analysis.yml b/.github/workflows/sonarcloud-analysis.yml
--- a/.github/workflows/sonarcloud-analysis.yml
+++ b/.github/workflows/sonarcloud-analysis.yml
@@ -72,10 +72,23 @@ jobs:
         continue-on-error: true
 
       - name: Integration tests coverage
+        id: integtests-coverage
         env:
           QT_QPA_PLATFORM: offscreen
         run: cmake --build build --target integtests-coverage
         continue-on-error: true
+
+      - name: Get coverage report paths
+        id: coverage-paths
+        run: |
+          unittests=$(find build -name unittests-coverage.xml)
+          integtests=$(find build -name integtests-coverage.xml)
+          paths="${unittests}${integtests:+,$integtests}"
+          if [ -z "$paths" ]; then
+            echo "Error: No coverage files found"
+            exit 1
+          fi
+          echo "csv=$paths" >> $GITHUB_OUTPUT
 
       - name: Run SonarScanner
         run: |
@@ -89,7 +102,7 @@ jobs:
             -Dsonar.exclusions=ext/**,build/** \
             -Dsonar.cfamily.build-wrapper-output=bw-output \
             -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.coverageReportPaths=build/coverage.xml \
+            -Dsonar.coverageReportPaths=${{ steps.coverage-paths.outputs.csv }} \
             -Dsonar.cfamily.threads=${{ env.CPU_CORE_COUNT }}
         env:
           SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
